### ISSUE TITLE
sftp-server is never linked out of the Cellar

### ISSUE THREAD

**Issue by grahams** [Homebrew/homebrew-dupes#494]
The homebrew recipe for OpenSSH never creates a symlink for sftp-server..  I was going to look into doing this myself when I realized that homebrew does not create /usr/local/libexec by default.  So I'm not exactly sure where to stick the symlink.

**Comment by DomT4** [comment]
Stuff in `libexec` inside a prefix isn't intended to be symlinked elsewhere - It's a kind of sandbox inside the formula's Cellar. That said, this isn't a deliberate choice by us.

We tell OpenSSH to install into `HOMEBREW_PREFIX/Cellar/openssh/version/` and OpenSSH places `sftp-server` in `libexec` regardless. This is also true of the Apple OpenSSH, which installs the server in `/usr/libexec/sftp-server`, which isn't in the `$PATH`. I'm presuming this is intended upstream behaviour.

There's some discussion on it [here](https://stackoverflow.com/questions/15741796/linux-how-to-start-sftp-server) for Linux, which is relevant. It looks like rather than being in the `$PATH` directly it is intended to be "called" from the configuration instead.

**Comment by grahams** [comment]
Is there a best practice for pointing to the correct sftp-server in sshd_config?  It seems like every time I do a 'brew cleanup' sftp breaks until I remember to update the config file (as it points to the Cellar path)...

**Comment by DomT4** [comment]
Use `/usr/local/opt/openssh/libexec` rather than `/usr/local/Cellar/openssh/xyz/libexec`. The former path will always point to the latest OpenSSH installation and won't break across updates/etc.

**Comment by grahams** [comment]
Perfect, thanks...
