### ISSUE TITLE
ssh-add doesn't support -K to add private key to OS X keychain

### ISSUE THREAD

**Issue by andrewpong** [Homebrew/homebrew-dupes#514]
Software versions:
* OS X 10.11.1
* brew 0.9.5 (git revision fa01; last commit 2015-09-18)
* openssh 7.1 p1

When I use ssh-add, it does not support -K, so I am unable to add the private key to the OS X keychain and have it autoload on reboots.

I think this is similar to issue #242. I apologize if this is not a valid issue and I simply misunderstand something!

```shell

ssh-add -K ~/.ssh/id_rsa
ssh-add: illegal option -- K
usage: ssh-add [options] [file ...]
Options:
  -l          List fingerprints of all identities.
  -E hash     Specify hash algorithm used for fingerprints.
  -L          List public key parameters of all identities.
  -k          Load only keys and not certificates.
  -c          Require confirmation to sign using identities
  -t life     Set lifetime (in seconds) when adding identities.
  -d          Delete identity.
  -D          Delete all identities.
  -x          Lock agent.
  -X          Unlock agent.
  -s pkcs11   Add keys from PKCS#11 provider.
  -e pkcs11   Remove keys provided by PKCS#11 provider.```

**Comment by DomT4** [comment]
We no longer support interaction with the OS X Keychain. Essentially if people want that specific functionality back they should try and get it worked into upstream officially and that way we're not waiting on unofficial patches to be updated & with no idea whether they remain fully functional and secure with each release.

You can of course also support your own `openssh` formula in a tap or locally with that functionality restored, although be aware on 10.11 you can't edit `/System` plists without disabling rootless.

If your primary reason for using `openssh` from Dupes is because the system ciphers are massively outdated, Apple updated `openssh` in OS X 10.11 and built it against LibreSSL, which should make available those newer ciphers that were lacking.

I'd recommend using something like `gpg-agent` which is capable of handling situations like these, as directed [here](https://github.com/Homebrew/homebrew-dupes/pull/482#issuecomment-119466100).
