### ISSUE TITLE
screen vertical splitting patch?

### ISSUE THREAD

**Issue by tonyxiao** [Homebrew/homebrew-dupes#619]
Automatically providing this functionality would be super handy

http://old.evanmeagher.net/2010/12/patching-screen-with-vertical-split-in-os

**Comment by apjanke** [comment]
We'd probably pass on a patch in this case, and ask that it be submitted upstream to the `screen` maintainers instead. Homebrew patches are mostly for working around build system problems, and not for porting functionality to OS X. It'd be better if the OS X support for this could be fixed in the main `screen` distribution.

**Comment by tonyxiao** [comment]
Got it. It just seemed like this fix has stalled for main screen distribution for quite some time. But point taken.
