### ISSUE TITLE
macOS 10.12 Broken Formulae

### ISSUE THREAD

**Issue by theeternalsw0rd** [Homebrew/homebrew-dupes#634]
homebrew-core has an issue for this, so why not homebrew-dupes.

Only one I am aware of is openssh. 
- `openssh`: https://gist.github.com/theeternalsw0rd/a870223128456315fea2844f4d74e158 - It has some sort of issue with declarations from the system vis.h.

**Comment by bfontaine** [comment]
Is it still an issue?

**Comment by tru** [comment]
Ah interesting I just ran into this problem as well. Yeah it's still a problem with upstream. It seems to been broken since sierra implemented `strnvis()` and that sets `HAVE_STRNVIS` which make the whole vis.h uncommented. I bet the right solution is to make it include `/usr/include/vis.h` instead, but that is going to be tricky to get the compiler to do that nicely.

**Comment by tru** [comment]
We worked around this in the following way: https://gist.github.com/79415553c372529fa6b32b56acf21d1c

**Comment by virussmca** [comment]
Hi Tru,
Is issue fixed? how to use this above work around?

**Comment by MikeMcQuaid** [comment]
These will be fixed when imported into Homebrew/core: https://github.com/Homebrew/homebrew-core/pull/11282
