### ISSUE TITLE
srm removed from sierra

### ISSUE THREAD

**Issue by keith** [Homebrew/homebrew-dupes#725]
Since the `srm` command was removed from macOS Sierra, I'm wondering if it make sense to either:

- Move `srm` to the `hombrew-core` repo? I'm not sure how this is handled for different versions of OS', but it's no longer a dup for Sierra and above

OR:

- Leave here but remove the `keg_only` attribute (at least for Sierra) so that users do not have to force link, since it no longer interferes with the system install.

Or something else?

**Comment by ilovezfs** [comment]
This repository will soon be deprecated, with everything moved to core and black-listed for use as dependencies.

Regarding `srm` specifically, I suspect we may just want to kill the command since Apple removed it to keep people from destroying their SSDs. It would be nice if the command were enhanced to refuse to operate if the target block device is a SSD because we're effectively assisting people with breaking their hardware by providing this formula.

**Comment by keith** [comment]
Thanks for the context! Maybe we should toss it entirely then and users will have to pull it from the history if they still want to install it 😬

**Comment by MikeMcQuaid** [comment]
> Regarding srm specifically, I suspect we may just want to kill the command since Apple removed it to keep people from destroying their SSDs.

Agreed 👍

**Comment by smileytechguy** [comment]
I agree that it shouldn't be used on SSDs, however I would like it to stay as I use it frequently to securely erase external drives

**Comment by MikeMcQuaid** [comment]
Sorry. Please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Thanks!
